install.packages("magrittr")
install.packages("shiny")
install.packages("DT")
install.packages("remotes")
install.packages("httr")
install.packages("glue")
install.packages("dplyr")
install.packages("purrr")
remotes::install_github("r-world-devs/shinyGizmo", ref = "dev")
