library(shiny)
library(glue)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      textInput("title", "Title"),
      numericInput("x_max", "Maximum x axis value", value = 10, min = 1),
      textInput("generated_by", "Generated by:")
    ),
    mainPanel(
      plotOutput("sine"),
      tableOutput("plot_table"),
      textOutput("gen_by")
    )
  )
)

server <- function(input, output, session) {
  output$sine <- renderPlot({
    plot_data <- data.frame(
      x = seq(0, input$x_max, by = 0.1),
      y = sin(seq(0, input$x_max, by = 0.1))
    )
    plot(plot_data$x, plot_data$y, main = input$title, type = "l")
  })
  
  output$plot_table <- renderTable({
    plot_data <- data.frame(
      x = seq(0, input$x_max, by = 0.1),
      y = sin(seq(0, input$x_max, by = 0.1))
    )
    plot_data
  })
  
  output$gen_by <- renderText({
    glue("Chart generated by {input$generated_by}")
  })
}

shinyApp(ui, server)